// lib/questionnaire/questions.ts — Question Set V3 per CURSOR_PROMPT_INTROSPECT_QUESTIONNAIRE_V1

import type { Question } from '@/types/questionnaire'

export const questions: Record<string, Question> = {
  q1_name: {
    id: 'q1_name',
    text: "What's your name?",
    inputType: 'text',
    required: true,
    placeholder: 'Your name',
    scopeField: 'S3.fullName',
  },
  q2_email: {
    id: 'q2_email',
    text: 'And your email address?',
    inputType: 'text',
    inputMode: 'email',
    required: true,
    placeholder: 'your@email.com',
    scopeField: 'S3.email',
  },
  q3_phone: {
    id: 'q3_phone',
    text: 'A phone number? (Optional)',
    inputType: 'text',
    inputMode: 'tel',
    required: false,
    skippable: true,
    placeholder: 'Your phone number',
    scopeField: 'S3.phone',
  },
  q4_business_name: {
    id: 'q4_business_name',
    text: "What's the name of your business or project?",
    inputType: 'text',
    required: true,
    placeholder: 'Business or project name',
    scopeField: ['S3.companyName', 'S1.projectName'],
  },
  q5_project_type: {
    id: 'q5_project_type',
    text: 'What are we building for you?',
    inputType: 'option_select',
    required: true,
    scopeField: ['S2.websiteType', 'S1.websiteType'],
    branchTrigger: true,
    options: [
      { value: 'service', label: 'Service business website', description: 'You offer a service — consulting, trades, health, beauty, legal, etc.' },
      { value: 'ecommerce', label: 'Online store', description: 'You sell physical or digital products' },
      { value: 'portfolio', label: 'Portfolio or showcase', description: 'You want to show your work — design, photography, contracting, etc.' },
      { value: 'restaurant', label: 'Restaurant or café', description: 'Menu, hours, reservations, ordering' },
      { value: 'nonprofit', label: 'Nonprofit or community organization', description: 'Donations, events, volunteer coordination' },
      { value: 'blog', label: 'Blog or content site', description: 'Regular articles, newsletter, content publishing' },
      { value: 'app', label: 'Web app or customer portal', description: 'Users log in, do things, see their own data' },
      { value: 'something_else', label: 'Something else', description: '', allowText: true },
    ],
  },
  q6_industry: {
    id: 'q6_industry',
    text: 'What industry are you in?',
    inputType: 'option_select',
    required: true,
    scopeField: ['S2.industry', 'S15.securityInput'],
    options: [
      { value: 'health_wellness', label: 'Health & wellness' },
      { value: 'home_services', label: 'Home services (trades, landscaping, cleaning)' },
      { value: 'food_beverage', label: 'Food & beverage' },
      { value: 'beauty_personal', label: 'Beauty & personal care' },
      { value: 'legal_financial', label: 'Legal or financial services' },
      { value: 'real_estate', label: 'Real estate' },
      { value: 'fitness', label: 'Fitness & sports' },
      { value: 'education', label: 'Education or coaching' },
      { value: 'creative_services', label: 'Creative services (design, photography, video)' },
      { value: 'automotive', label: 'Automotive (repair, detailing, sales)' },
      { value: 'retail', label: 'Retail' },
      { value: 'nonprofit', label: 'Nonprofit or community' },
      { value: 'tech', label: 'Technology' },
      { value: 'something_else', label: 'Something else', allowText: true },
    ],
  },
  q7_primary_goal: {
    id: 'q7_primary_goal',
    text: "When someone lands on your site, what's the ONE thing you want them to do?",
    inputType: 'option_select',
    required: true,
    scopeField: ['S1.primaryGoal', 'S4.primaryGoal'],
    options: [
      { value: 'call_contact', label: 'Call or message me' },
      { value: 'book_appointment', label: 'Book an appointment' },
      { value: 'buy_something', label: 'Buy something' },
      { value: 'get_a_quote', label: 'Request a quote' },
      { value: 'find_my_location', label: 'Find my location or hours' },
      { value: 'learn_trust', label: 'Learn about me and reach out when ready' },
      { value: 'sign_up', label: 'Sign up or create an account' },
      { value: 'something_else', label: 'Something else', allowText: true },
    ],
  },
  q8_existing_website: {
    id: 'q8_existing_website',
    text: 'Do you already have a website?',
    inputType: 'option_select',
    required: true,
    scopeField: ['S4.companyOverview', 'S12.risks'],
    options: [
      { value: 'yes_migrate', label: 'Yes, and I want to bring content across from it' },
      { value: 'yes_replace', label: 'Yes, but I want to start completely fresh' },
      { value: 'no', label: 'No, this is my first one' },
    ],
    branchLogic: {
      yes_migrate: ['q8a_current_url', 'q8b_frustrations'],
      yes_replace: ['q8a_current_url', 'q8b_frustrations'],
      no: [],
    },
  },
  q8a_current_url: {
    id: 'q8a_current_url',
    text: "What's the address?",
    inputType: 'text',
    inputMode: 'url',
    required: false,
    condition: { questionId: 'q8_existing_website', notValue: 'no' },
    placeholder: 'https://yoursite.com',
    scopeField: 'S4.existingSiteUrl',
  },
  q8b_frustrations: {
    id: 'q8b_frustrations',
    text: "What's the biggest thing that isn't working about it right now?",
    inputType: 'option_select',
    required: false,
    condition: { questionId: 'q8_existing_website', notValue: 'no' },
    scopeField: 'S4.painPoints',
    options: [
      { value: 'looks_outdated', label: 'It looks outdated' },
      { value: 'hard_to_update', label: "It's hard for me to update myself" },
      { value: 'not_showing_up', label: "It's not showing up on Google" },
      { value: 'not_bringing_business', label: "It's just not bringing in business" },
      { value: 'not_mobile', label: "It doesn't work well on phones" },
      { value: 'slow', label: 'It loads too slowly' },
      { value: 'something_else', label: 'Something else', allowText: true },
    ],
  },
  q9_logo: {
    id: 'q9_logo',
    text: "Do you have a logo you're happy with?",
    inputType: 'option_select',
    required: true,
    scopeField: ['S5.existingAssets.logo', 'S5.whatNeedsCreation'],
    options: [
      { value: 'yes', label: 'Yes, and I have the original files' },
      { value: 'yes_no_files', label: 'Yes, but I only have a screenshot or low-res version' },
      { value: 'yes_ok', label: 'I have one, but it could be better' },
      { value: 'no', label: 'No, I need one' },
    ],
  },
  q10_brand_colors: {
    id: 'q10_brand_colors',
    text: 'Do you have specific colors that belong to your brand?',
    inputType: 'option_select',
    required: true,
    scopeField: 'S5.existingAssets.colorPalette',
    options: [
      { value: 'yes_exact', label: 'Yes — I have exact colors (hex codes or brand guidelines)' },
      { value: 'yes_general', label: 'Sort of — I have colors I use but nothing official' },
      { value: 'no', label: "No, I'm open to direction" },
    ],
    branchLogic: {
      yes_exact: ['q10a_color_entry'],
      yes_general: ['q10a_color_entry'],
      no: [],
    },
  },
  q10a_color_entry: {
    id: 'q10a_color_entry',
    text: "What are they? Hex codes, names, or just describe them — whatever you have.",
    inputType: 'color',
    required: false,
    condition: { questionId: 'q10_brand_colors', notValue: 'no' },
    placeholder: 'e.g. #2D5BE3, or "navy blue and warm gold"',
    scopeField: ['S5.colorPaletteDetails', 'S9.colorScheme'],
  },
  q11_photography: {
    id: 'q11_photography',
    text: 'Do you have photos ready to use?',
    inputType: 'option_select',
    required: true,
    scopeField: ['S5.existingAssets.imagery', 'S6.photographyNeeded', 'S8.galleries'],
    options: [
      { value: 'have_great', label: 'Yes — I have professional photos ready to go' },
      { value: 'have_ok', label: 'I have some, but they could be better' },
      { value: 'need_photos', label: 'No — I need photography arranged' },
      { value: 'stock_ok', label: 'Stock photos are fine for now' },
    ],
  },
  q12_media: {
    id: 'q12_media',
    text: 'Does your site need any video or interactive features?',
    inputType: 'option_select',
    multiSelect: true,
    required: false,
    scopeField: ['S8.video', 'S8.interactiveElements'],
    options: [
      { value: 'no', label: 'No, none of that' },
      { value: 'yes_embed', label: 'A YouTube or Vimeo video embedded on the page' },
      { value: 'yes_background', label: 'A background video behind the hero section' },
      { value: 'yes_interactive', label: 'Something interactive — a calculator, quiz, or configurator' },
      { value: 'not_sure', label: 'Not sure yet' },
    ],
  },
  q13_inspiration: {
    id: 'q13_inspiration',
    text: 'Any websites you love the look of? Drop the links here.',
    inputType: 'url_list',
    required: false,
    skippable: true,
    placeholder: 'https://example.com',
    helpText: 'Competitors, businesses you admire, anyone — optional but helpful.',
    scopeField: 'S9.references',
  },
  q14_design_style: {
    id: 'q14_design_style',
    text: "How would you describe the look and feel you're going for?",
    inputType: 'option_select',
    multiSelect: true,
    multiSelectMax: 3,
    required: true,
    scopeField: ['S9.overallStyle', 'S9.designPriorities'],
    options: [
      { value: 'clean_minimal', label: 'Clean and minimal' },
      { value: 'bold_striking', label: 'Bold and striking' },
      { value: 'warm_friendly', label: 'Warm and approachable' },
      { value: 'professional_polished', label: 'Professional and polished' },
      { value: 'modern_technical', label: 'Modern and technical' },
      { value: 'classic_traditional', label: 'Classic and traditional' },
      { value: 'playful_fun', label: 'Playful and fun' },
      { value: 'luxury_premium', label: 'Luxury and high-end' },
    ],
  },
  q15_styles_avoid: {
    id: 'q15_styles_avoid',
    text: "Anything you definitely don't want? (Optional)",
    inputType: 'text',
    required: false,
    skippable: true,
    placeholder: 'e.g. "No dark backgrounds" or "nothing too corporate"',
    scopeField: 'S9.designConstraints',
  },
  q16_integrations: {
    id: 'q16_integrations',
    text: 'Are there any tools or services your new site needs to connect with?',
    subtext: 'Think booking systems, email platforms, payment processors, or anything else your business already runs on.',
    inputType: 'option_select',
    multiSelect: true,
    required: false,
    scopeField: 'S7.integrations',
    options: [
      { value: 'booking_system', label: 'A booking or scheduling system (Calendly, Acuity, Vagaro, etc.)', allowText: true },
      { value: 'email_marketing', label: 'An email platform (Mailchimp, Klaviyo, etc.)', allowText: true },
      { value: 'crm', label: 'A CRM or customer management system', allowText: true },
      { value: 'payment_processor', label: 'A payment processor you already use (Square, Stripe, PayPal)', allowText: true },
      { value: 'pos_system', label: 'A point-of-sale system', allowText: true },
      { value: 'accounting', label: 'Accounting software (QuickBooks, Xero, etc.)', allowText: true },
      { value: 'social_media', label: 'Social media feeds or sharing' },
      { value: 'analytics', label: 'Google Analytics or similar' },
      { value: 'none', label: 'None — starting fresh' },
      { value: 'something_else', label: 'Something else', allowText: true },
    ],
  },
  q17_content_writer: {
    id: 'q17_content_writer',
    text: "Who's going to write the words on your website?",
    inputType: 'option_select',
    required: true,
    scopeField: ['S6.contentProvider', 'S6.copywritingNeeded'],
    options: [
      { value: 'me', label: "I'll write them myself" },
      { value: 'you', label: "I'd like help with that" },
      { value: 'mixed', label: 'A bit of both' },
      { value: 'have_it', label: 'I already have most of it written' },
    ],
  },
  q18_update_frequency: {
    id: 'q18_update_frequency',
    text: 'After launch, how often will you need to update the content?',
    inputType: 'option_select',
    required: true,
    scopeField: ['S6.updateFrequency', 'S7.contentManagement', 'S11.maintenancePlan'],
    options: [
      { value: 'rarely', label: 'Rarely', description: 'Prices, hours, contact info — that\'s about it' },
      { value: 'monthly', label: 'Every month or so', description: 'New photos, updated services, occasional news' },
      { value: 'weekly', label: 'Weekly', description: 'Blog posts, promotions, new inventory' },
      { value: 'daily', label: 'Daily or more', description: 'Active store, daily content, live inventory' },
    ],
  },
  q19_support: {
    id: 'q19_support',
    text: 'After launch, how do you want to handle updates and maintenance?',
    inputType: 'option_select',
    required: true,
    scopeField: ['S11.maintenancePlan', 'S11.hosting'],
    options: [
      { value: 'handle_it', label: "I'll handle it myself", description: 'Full control — you manage updates and hosting' },
      { value: 'some_help', label: 'Some help would be nice', description: 'Occasional support when you need it' },
      { value: 'handle_it_for_me', label: "Handle it for me — I don't want to think about it", description: 'Fully managed hosting and maintenance' },
    ],
  },
  q20_domain: {
    id: 'q20_domain',
    text: 'Do you already have a domain name?',
    inputType: 'option_select',
    required: true,
    scopeField: 'S7.domain',
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No, I need one' },
      { value: 'not_sure', label: 'Not sure' },
    ],
    branchLogic: {
      yes: ['q20a_domain_entry'],
      no: [],
      not_sure: [],
    },
  },
  q20a_domain_entry: {
    id: 'q20a_domain_entry',
    text: 'What is it?',
    inputType: 'text',
    required: false,
    condition: { questionId: 'q20_domain', value: 'yes' },
    placeholder: 'yourdomain.com',
    scopeField: 'S7.domainName',
  },
  q21_timeline: {
    id: 'q21_timeline',
    text: 'When are you looking to launch?',
    inputType: 'option_select',
    required: true,
    scopeField: ['S12.desiredLaunchDate', 'S12.risks'],
    options: [
      { value: 'asap', label: 'As soon as possible' },
      { value: '1_2_months', label: 'Within 1–2 months' },
      { value: '3_months', label: 'Around 3 months' },
      { value: 'flexible', label: 'No hard deadline — just do it right' },
      { value: 'specific_date', label: 'I have a specific date in mind' },
    ],
    branchLogic: {
      specific_date: ['q21a_specific_date'],
    },
  },
  q21a_specific_date: {
    id: 'q21a_specific_date',
    text: "What's the date?",
    inputType: 'date',
    required: false,
    condition: { questionId: 'q21_timeline', value: 'specific_date' },
    scopeField: 'S12.launchDate',
  },
  q22_budget: {
    id: 'q22_budget',
    text: 'To build the right plan, I need to understand your investment range.',
    subtext: "Everything we've talked about is possible — the budget just shapes the scope and timeline.",
    inputType: 'option_select',
    required: true,
    scopeField: ['S2.recommendedPackage', 'S13.basePackage'],
    options: [
      { value: 'starter', label: 'Starter — $2,500', description: 'Clean, focused, everything you need to launch' },
      { value: 'professional', label: 'Professional — $4,500', description: 'More pages, more features, more polish' },
      { value: 'custom', label: 'Custom — $6,000+', description: 'Built specifically around your vision' },
      { value: 'not_sure', label: "I'm not sure yet", description: "I'll recommend what makes sense based on everything you've shared" },
    ],
  },
  q23_competitors: {
    id: 'q23_competitors',
    text: 'Who are your main competitors?',
    subtext: "Seeing their sites helps us make sure yours stands out. Names or website addresses both work.",
    inputType: 'text',
    required: false,
    skippable: true,
    placeholder: 'e.g. "Smith Plumbing, acmeservices.com"',
    scopeField: ['S1.competitorContext', 'S9.competitiveLandscape'],
  },
  q24_anything_else: {
    id: 'q24_anything_else',
    text: "Last one — anything else we should know before we get started?",
    inputType: 'text',
    required: false,
    skippable: true,
    placeholder: 'Anything at all...',
    scopeField: ['S14.assumptionsClarified', 'S4.additionalContext'],
  },
  // E-commerce branch
  qe1_product_count: {
    id: 'qe1_product_count',
    text: 'How many products are you planning to sell?',
    inputType: 'option_select',
    required: true,
    branch: 'ecommerce',
    scopeField: 'S7.productCatalog.size',
    options: [
      { value: 'under_20', label: 'Under 20' },
      { value: '20_100', label: '20–100' },
      { value: '100_500', label: '100–500' },
      { value: '500_plus', label: '500+' },
      { value: 'not_sure', label: 'Not sure yet' },
    ],
  },
  qe2_variants: {
    id: 'qe2_variants',
    text: 'Do your products come in variations — like sizes, colors, or styles?',
    inputType: 'option_select',
    required: true,
    branch: 'ecommerce',
    scopeField: 'S7.productCatalog.variants',
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No, each product is one thing' },
      { value: 'some', label: "Some do, some don't" },
    ],
  },
  qe3_inventory: {
    id: 'qe3_inventory',
    text: 'Do you need to track stock levels — so things automatically show as out of stock?',
    inputType: 'option_select',
    required: true,
    branch: 'ecommerce',
    scopeField: 'S7.productCatalog.inventory',
    options: [
      { value: 'yes', label: 'Yes, definitely' },
      { value: 'no', label: "No, I'll manage that manually" },
      { value: 'not_sure', label: 'Not sure yet' },
    ],
  },
  qe4_payment_methods: {
    id: 'qe4_payment_methods',
    text: 'How do you want customers to pay?',
    inputType: 'option_select',
    multiSelect: true,
    required: true,
    branch: 'ecommerce',
    scopeField: 'S7.payments.methods',
    options: [
      { value: 'card', label: 'Credit / debit card' },
      { value: 'apple_google_pay', label: 'Apple Pay / Google Pay' },
      { value: 'buy_now_pay_later', label: 'Buy now, pay later (Afterpay, Klarna)' },
      { value: 'invoice', label: 'Invoice / pay later' },
    ],
  },
  // App branch
  qa1_who_logs_in: {
    id: 'qa1_who_logs_in',
    text: 'Who needs to log in to your app?',
    inputType: 'option_select',
    required: true,
    branch: 'app',
    scopeField: ['S7.authentication', 'S7.userRoles'],
    options: [
      { value: 'just_me', label: "Just me — it's an admin tool" },
      { value: 'customers', label: 'My customers' },
      { value: 'both', label: 'Both me and my customers, with different access' },
      { value: 'team', label: 'My team or staff' },
      { value: 'all_three', label: 'Me, my team, and my customers' },
    ],
  },
  qa2_account_actions: {
    id: 'qa2_account_actions',
    text: 'What can a logged-in customer actually do?',
    inputType: 'option_select',
    multiSelect: true,
    required: true,
    branch: 'app',
    scopeField: ['S7.userRoles.permissions', 'S7.websiteTypeFeatures'],
    options: [
      { value: 'view_history', label: 'View their order or appointment history' },
      { value: 'manage_bookings', label: 'Manage their own bookings' },
      { value: 'download_files', label: 'Download files or documents' },
      { value: 'message_you', label: 'Message you directly' },
      { value: 'manage_subscription', label: 'Manage their subscription' },
      { value: 'update_profile', label: 'Update their own profile or information' },
      { value: 'something_else', label: 'Something else', allowText: true },
    ],
  },
  qa3_business_logic: {
    id: 'qa3_business_logic',
    text: "Walk me through how a typical transaction works — from a customer's perspective, step by step.",
    inputType: 'textarea',
    required: true,
    branch: 'app',
    scopeField: ['S7.businessLogic', 'S4.companyOverview'],
    placeholder: 'e.g. "A customer browses services → picks a time → pays a deposit → gets a confirmation email → shows up for their appointment."',
    helpText: 'Write it exactly like that — plain steps, in order. This is the most important question for your app.',
  },
  qa4_data_sensitivity: {
    id: 'qa4_data_sensitivity',
    text: 'Does your app handle any sensitive information?',
    inputType: 'option_select',
    multiSelect: true,
    required: true,
    branch: 'app',
    scopeField: ['S7.compliance', 'S15.securityClassification'],
    options: [
      { value: 'health_records', label: 'Health or medical records' },
      { value: 'payment_data', label: 'Payment or financial data' },
      { value: 'personal_ids', label: 'Personal IDs or government documents' },
      { value: 'private_messages', label: 'Private messages between users' },
      { value: 'none', label: 'Nothing particularly sensitive' },
    ],
  },
  // Content branch
  qc1_content_types: {
    id: 'qc1_content_types',
    text: 'What kind of content will you be publishing?',
    inputType: 'option_select',
    multiSelect: true,
    required: true,
    branch: 'content',
    scopeField: ['S6.contentTypes', 'S7.websiteTypeFeatures'],
    options: [
      { value: 'articles', label: 'Articles or blog posts' },
      { value: 'newsletters', label: 'Email newsletters' },
      { value: 'podcasts', label: 'Podcast episodes' },
      { value: 'videos', label: 'Video content' },
      { value: 'case_studies', label: 'Case studies or project write-ups' },
      { value: 'product_updates', label: 'Product or service updates' },
    ],
  },
  qc2_multiple_authors: {
    id: 'qc2_multiple_authors',
    text: 'Will more than one person be publishing content?',
    inputType: 'option_select',
    required: true,
    branch: 'content',
    scopeField: ['S7.contentManagement.editors', 'S6.editorialWorkflow'],
    options: [
      { value: 'just_me', label: 'Just me' },
      { value: 'small_team', label: 'A small team (2–5 people)' },
      { value: 'larger_team', label: 'A larger team or contributors' },
    ],
  },
}
