// lib/questions/questionBank.ts — All 33 questions per INTROSPECT spec

import type { Question } from '@/types/questions'

export const QUESTIONS: Question[] = [
  // Page 1 — Let's Meet You (Q1–Q4)
  {
    id: 'q1_name',
    type: 'text',
    text: "What's your name?",
    placeholder: 'First and last name',
    required: true,
  },
  {
    id: 'q2_email',
    type: 'email',
    text: "And your email address?",
    placeholder: 'you@example.com',
    helperText: "We'll send your proposal here — so make it a good one.",
    required: true,
  },
  {
    id: 'q3_phone',
    type: 'phone',
    text: "A phone number? (Totally optional)",
    placeholder: '(555) 123-4567',
    helperText: "We only call if something's unclear — and we'll always text first.",
    required: false,
  },
  {
    id: 'q4_business_name',
    type: 'text',
    text: "What's the name of your business or project?",
    placeholder: "e.g., Blue Ridge Bakery, My Photography Studio, Jake's Consulting",
    helperText: "Doesn't have to be official — even a working name is fine.",
    required: true,
  },
  // Page 2 — About Your Project (Q5–Q6)
  {
    id: 'q5_website_type',
    type: 'single_select',
    text: 'What kind of website are you looking for?',
    helperText: "Pick the one that feels closest — we'll figure out the details together.",
    required: true,
    options: [
      { value: 'business', label: 'A website for my business or services' },
      { value: 'ecommerce', label: 'An online store to sell things' },
      { value: 'portfolio', label: 'A portfolio to show off my work' },
      { value: 'nonprofit', label: 'A site for my non-profit or community cause' },
      { value: 'blog', label: 'A blog or place to share content' },
      { value: 'landing_page', label: 'One focused landing page' },
    ],
    otherOption: true,
  },
  {
    id: 'q6_industry',
    type: 'single_select',
    text: 'What world do you operate in?',
    helperText: 'Just pick the closest fit — this helps us ask smarter questions.',
    required: true,
    options: [
      { value: 'professional_services', label: 'Law, finance, or consulting' },
      { value: 'healthcare', label: 'Healthcare or wellness' },
      { value: 'real_estate', label: 'Real estate or property' },
      { value: 'construction', label: 'Construction, trades, or home services' },
      { value: 'food_beverage', label: 'Restaurants, food, or hospitality' },
      { value: 'creative', label: 'Design, photography, or creative work' },
      { value: 'technology', label: 'Tech or software' },
      { value: 'education', label: 'Education or coaching' },
      { value: 'retail', label: 'Retail or product sales' },
      { value: 'nonprofit_sector', label: 'Non-profit or community' },
      { value: 'beauty_wellness', label: 'Beauty, fitness, or personal care' },
      { value: 'hospitality', label: 'Events or entertainment' },
    ],
    otherOption: true,
  },
  // Page 3 — What You're Going For (Q7–Q10)
  {
    id: 'q7_primary_goal',
    type: 'single_select',
    text: "When someone visits your new website, what's the ONE thing you want to happen?",
    helperText: "If you could only have one outcome, what would it be?",
    required: true,
    options: [
      { value: 'contact_quote', label: 'They pick up the phone and call me (or fill out a form)' },
      { value: 'purchase', label: "They buy something right then and there" },
      { value: 'hire_me', label: "They're impressed and decide to hire me" },
      { value: 'sign_up', label: 'They sign up, join, or subscribe to something' },
      { value: 'build_trust', label: 'They trust me more than my competitors' },
      { value: 'find_info', label: 'They find the exact information they came for' },
      { value: 'donate', label: 'They donate to or support my cause' },
    ],
    otherOption: true,
  },
  {
    id: 'q9_target_audience',
    type: 'single_select',
    text: "Who are the people you most want to walk through your (virtual) front door?",
    helperText: "Think about your favorite type of customer or the people you most want to reach.",
    required: true,
    options: [
      { value: 'local_consumers', label: 'People in my local area' },
      { value: 'national_consumers', label: 'Customers anywhere in the country' },
      { value: 'businesses_b2b', label: 'Other businesses (I work B2B)' },
      { value: 'professionals', label: 'Professionals or specialists in my field' },
      { value: 'community', label: 'A community of like-minded people' },
      { value: 'mix', label: 'Honestly, a pretty mixed crowd' },
    ],
    otherOption: true,
  },
  {
    id: 'q10_differentiator',
    type: 'textarea',
    text: "Here's a fun one: why would someone choose YOU over everyone else doing what you do?",
    placeholder:
      "e.g., I've been doing this for 20 years, I actually answer the phone, my prices are fair, my work speaks for itself...",
    helperText: "What do your best customers say about you? What makes you genuinely different? Brag a little — we won't judge.",
    required: true,
    minLength: 30,
  },
  // Page 4 — Websites You Love (Q11–Q13)
  {
    id: 'q11_inspiration_urls',
    type: 'url_list',
    text: 'Any websites you love? Paste the links here.',
    helperText:
      "They don't have to be in your industry — just sites that make you think 'I want something that feels like this.' Up to 5 links.",
    placeholder: 'https://example.com',
    required: false,
  },
  {
    id: 'q12_inspiration_styles',
    type: 'multi_select',
    text: "What is it about those sites that you love? (Or just vibe with in general)",
    helperText: "Select everything that resonates — even if you didn't add any links above.",
    required: false,
    options: [
      { value: 'clean_simple', label: 'Clean and uncluttered — room to breathe' },
      { value: 'professional_trustworthy', label: 'Professional and trust-building — serious business energy' },
      { value: 'bold_eyecatching', label: 'Bold and impossible to ignore' },
      { value: 'easy_navigation', label: 'Easy to navigate — I always know where I am' },
      { value: 'beautiful_photos', label: 'Stunning photography and visuals' },
      { value: 'modern_fresh', label: 'Modern and fresh — not dated at all' },
      { value: 'clear_messaging', label: "Crystal clear — I immediately get what they do" },
      { value: 'mobile_first', label: 'Works beautifully on my phone' },
      { value: 'fast_responsive', label: 'Fast — blink and it loads' },
    ],
    otherOption: true,
  },
  {
    id: 'q13_styles_to_avoid',
    type: 'multi_select',
    text: "Anything you definitely DON'T want? Hard nos, pet peeves, things that drive you crazy on other websites?",
    helperText: "Totally optional, but super helpful. Don't hold back.",
    required: false,
    options: [
      { value: 'not_corporate', label: 'Nothing too corporate' },
      { value: 'no_dark', label: 'No dark mode' },
      { value: 'not_cluttered', label: "Not cluttered like my competitor's site" },
      { value: 'no_busy', label: 'No busy or overwhelming layouts' },
      { value: 'no_generic', label: "Don't want a generic template look" },
      { value: 'no_flashy', label: 'No flashy animations or effects' },
      { value: 'no_minimal', label: "Don't want it too minimal or sparse" },
      { value: 'no_playful', label: 'Nothing too playful or casual' },
    ],
    otherOption: true,
  },
  // Page 5 — Where You're Starting From (Q14–Q16)
  {
    id: 'q14_has_website',
    type: 'single_select',
    text: 'Do you already have a website?',
    required: true,
    options: [
      { value: 'yes', label: 'Yes, I have one' },
      { value: 'no', label: 'Nope — starting from scratch' },
    ],
  },
  {
    id: 'q15_existing_url',
    type: 'url',
    text: "What's the address?",
    placeholder: 'https://www.yoursite.com',
    required: false,
    showIf: (answers) => answers['q14_has_website']?.value === 'yes',
  },
  {
    id: 'q16_existing_frustrations',
    type: 'multi_select',
    text: "What's not working about it? (Select everything that applies)",
    helperText: "Be brutal — this helps us understand exactly what needs to change.",
    required: false,
    showIf: (answers) => answers['q14_has_website']?.value === 'yes',
    options: [
      { value: 'looks_outdated', label: "It looks like it was built in 2012" },
      { value: 'not_mobile', label: 'Looks terrible on phones' },
      { value: 'cant_update', label: "I can't update it without calling someone" },
      { value: 'not_in_google', label: "Google doesn't know it exists" },
      { value: 'not_converting', label: 'Visitors come and go without doing anything' },
      { value: 'loads_slowly', label: 'It takes forever to load' },
      { value: 'confusing', label: "Nobody can tell what I actually do" },
      { value: 'embarrassing', label: "I'm embarrassed to hand out my business card" },
      { value: 'technical_issues', label: "It's constantly broken or hacked" },
    ],
    otherOption: true,
  },
  // Page 6 — Your Brand (Q17–Q20)
  {
    id: 'q17_has_logo',
    type: 'single_select',
    text: 'Do you have a logo you\'re happy with?',
    required: true,
    options: [
      { value: 'yes_professional', label: "Yes — it's professional and I love it" },
      { value: 'yes_needs_work', label: 'I have one, but honestly it could be better' },
      { value: 'no', label: "No logo yet — I'll need one" },
      { value: 'not_sure', label: 'Honestly not sure' },
    ],
  },
  {
    id: 'q18_has_colors',
    type: 'single_select',
    text: 'Do you have specific colors that belong to your brand?',
    required: true,
    options: [
      { value: 'yes', label: 'Yes — I know my exact colors' },
      { value: 'no', label: "Not really — I'm open to what looks great" },
      { value: 'not_sure', label: 'Kind of — I have preferences but nothing locked in' },
    ],
  },
  {
    id: 'q19_brand_colors',
    type: 'color_picker',
    text: "What are they? (As specific or vague as you like)",
    placeholder:
      "e.g., 'Navy #1a2b6b and gold', 'Same green as Starbucks', 'Deep blues and warm grays', 'I have a brand guide I can share later'",
    helperText: 'Search and select your colors, or enter a custom hex code.',
    required: false,
    showIf: (answers) => answers['q18_has_colors']?.value === 'yes',
  },
  {
    id: 'q20_has_photos',
    type: 'single_select',
    text: "What's your photo situation?",
    required: true,
    options: [
      { value: 'yes_professional', label: 'I have professional photos ready to use' },
      { value: 'yes_casual', label: "I have photos, but they're more iPhone than Annie Leibovitz" },
      { value: 'no', label: "No photos — I'll need stock images or to hire a photographer" },
    ],
  },
  // Page 7 — Content & Pages (Q21–Q23)
  {
    id: 'q21_content_provider',
    type: 'single_select',
    text: "Who's going to write the actual words on your website?",
    helperText: 'The about page, the services descriptions, all that copy.',
    required: true,
    options: [
      { value: 'client', label: "I'll write it — just need a direction to follow" },
      { value: 'collaborative', label: "I'd love help with that — can you write it for me?" },
      { value: 'agency', label: 'I already have a copywriter handling it' },
    ],
  },
  {
    id: 'q22_update_frequency',
    type: 'single_select',
    text: "Once the site is live, how often will you need to update it?",
    required: true,
    options: [
      {
        value: 'regularly',
        label: 'All the time — I\'ll want to add things regularly',
      },
      {
        value: 'occasionally',
        label: 'A few times a year — seasonal stuff, announcements',
      },
      {
        value: 'rarely',
        label: 'Rarely — once it\'s up, it\'s mostly up',
      },
    ],
  },
  {
    id: 'q23_pages_needed',
    type: 'multi_select',
    text: "Which of these pages do you imagine on your site? (Grab everything that sounds right)",
    required: true,
    options: [
      { value: 'home', label: 'Home page' },
      { value: 'about', label: 'About us / Our story' },
      { value: 'services', label: 'Services or what we offer' },
      { value: 'portfolio', label: 'Work samples or portfolio' },
      { value: 'products', label: 'Products or shop' },
      { value: 'blog', label: 'Blog or news' },
      { value: 'testimonials', label: 'Customer reviews or testimonials' },
      { value: 'team', label: 'Meet the team' },
      { value: 'faq', label: 'FAQ' },
      { value: 'contact', label: 'Contact page' },
      { value: 'pricing', label: 'Pricing' },
      { value: 'booking', label: 'Book an appointment' },
    ],
  },
  // Page 8 — Features & Functions (Q24–Q26)
  {
    id: 'q24_key_features',
    type: 'multi_select',
    text: "Which of these would make your website way more useful? (Pick everything that excites you)",
    helperText: "Don't filter yourself by cost yet — just tell us what you want.",
    required: false,
    options: [
      { value: 'contact_form', label: 'A contact form so people can reach me' },
      { value: 'online_booking', label: 'Online booking — let people schedule with me 24/7' },
      { value: 'ecommerce_store', label: 'A full online store with shopping cart' },
      { value: 'user_accounts', label: 'Customer accounts so people can log in' },
      { value: 'live_chat', label: 'Live chat so I can talk to visitors in real time' },
      { value: 'blog_cms', label: 'A blog or content section I can update myself' },
      { value: 'email_newsletter', label: 'Email newsletter sign-up' },
      { value: 'photo_gallery', label: 'A photo gallery or portfolio display' },
      { value: 'video_embed', label: 'Video integration (YouTube, Vimeo, etc.)' },
      { value: 'google_maps', label: 'A map showing where I\'m located' },
      { value: 'social_feed', label: 'Pull in my Instagram or social media feed' },
      { value: 'reviews_testimonials', label: 'Display my Google or Yelp reviews automatically' },
      { value: 'payment_processing', label: 'Accept payments (not a full store — just one-off payments)' },
      { value: 'quote_calculator', label: 'A quote calculator or pricing estimator' },
      { value: 'multilingual', label: 'Multiple languages' },
    ],
  },
  {
    id: 'q25_ecommerce_details',
    type: 'single_select',
    text: 'Nice — how many products are you planning to sell?',
    required: false,
    showIf: (answers) => {
      const features = (answers['q24_key_features']?.value as string[]) || []
      return (
        features.includes('ecommerce_store') || answers['q5_website_type']?.value === 'ecommerce'
      )
    },
    options: [
      { value: 'small', label: 'Small shop — under 25 products' },
      { value: 'medium', label: 'Medium catalog — 25 to 200 products' },
      { value: 'large', label: 'Big operation — 200+ products' },
    ],
  },
  {
    id: 'q26_integrations',
    type: 'multi_select',
    text: 'Are there any tools or services your website needs to connect with?',
    required: false,
    options: [
      { value: 'google_analytics', label: 'Google Analytics (to track visitors)' },
      { value: 'mailchimp', label: 'Mailchimp or another email platform' },
      { value: 'crm', label: 'A CRM like Salesforce or HubSpot' },
      { value: 'payment_stripe', label: 'Stripe (for payments)' },
      { value: 'payment_paypal', label: 'PayPal (for payments)' },
      { value: 'calendly', label: 'Calendly or another scheduling tool' },
      { value: 'social_media', label: 'My social media accounts' },
      { value: 'quickbooks', label: 'QuickBooks or accounting software' },
      { value: 'none', label: 'Nothing I can think of right now' },
    ],
  },
  // Page 9 — Timing & Budget (Q27–Q30)
  {
    id: 'q27_domain_status',
    type: 'single_select',
    text: 'Do you already have a domain name? (Like www.yourbusiness.com)',
    required: true,
    options: [
      { value: 'have_domain', label: 'Yes — I own one already' },
      { value: 'need_domain', label: 'No — I\'ll need to get one' },
      { value: 'not_sure', label: 'Not sure what I have' },
    ],
  },
  {
    id: 'q28_existing_domain',
    type: 'url',
    text: 'What is it?',
    placeholder: 'www.yourbusiness.com',
    required: false,
    showIf: (answers) => answers['q27_domain_status']?.value === 'have_domain',
  },
  {
    id: 'q29_timeline',
    type: 'single_select',
    text: 'How soon are you hoping to launch?',
    required: true,
    options: [
      { value: 'asap', label: 'Yesterday — I needed this yesterday' },
      { value: 'one_month', label: 'Within a month if possible' },
      { value: 'two_three_months', label: '2–3 months is fine' },
      { value: 'flexible', label: "I'm flexible — quality over speed" },
      { value: 'specific_date', label: 'I have a specific date in mind' },
    ],
  },
  {
    id: 'q30_budget',
    type: 'single_select',
    text: 'What kind of budget are you working with?',
    helperText: 'This helps us point you toward the right package. All options include the first year of hosting.',
    required: true,
    options: [
      { value: 'under_2500', label: 'Under $2,500 — keeping it lean' },
      { value: '2500_4500', label: '$2,500–$4,500 — solid professional site' },
      { value: '4500_plus', label: '$4,500+ — full-featured, custom build' },
      { value: 'not_sure', label: 'Not sure yet — show me what makes sense' },
    ],
  },
  // Page 10 — Last Things (Q31–Q33)
  {
    id: 'q31_competitors',
    type: 'textarea',
    text: "Who are your biggest competitors? (Optional, but really useful)",
    placeholder:
      "e.g., Smith Roofing (smithroofing.com), that other bakery on Oak Street, the big national chain we're competing against...",
    helperText:
      "Names, websites, or just descriptions. We do a little competitive research so your site stands out from them — not blend in.",
    required: false,
  },
  {
    id: 'q32_accessibility',
    type: 'single_select',
    text: 'Any specific accessibility requirements?',
    helperText: 'Things like ADA compliance, WCAG standards, or serving users with disabilities.',
    required: true,
    options: [
      {
        value: 'standard',
        label: 'Standard accessibility is fine — just make it usable for everyone',
      },
      {
        value: 'wcag_aa',
        label: 'I need full WCAG 2.1 AA compliance (government, healthcare, or education)',
      },
      { value: 'not_sure', label: "Not sure — tell me what you'd recommend" },
    ],
  },
  {
    id: 'q33_anything_else',
    type: 'textarea',
    text: "Last one — anything else we should know before we get to work?",
    placeholder: 'Anything at all...',
    helperText:
      "Wild ideas, specific concerns, things that didn't fit anywhere else, questions you have for us. The floor is yours.",
    required: false,
  },
]
